apiVersion: v1
kind: Pod
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  containers:
  - name: mysql-master
    image: mysql-master:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    - name: MYSQL_REPLICATION_USER
      value: "repl"
    - name: MYSQL_REPLICATION_PASSWORD
      value: "repl"
    ports:
    - containerPort: 3306
